import random
import math  # <--- ADDED THIS
from PIL import Image, ImageDraw, ImageFont, ImageOps

# --- CONFIGURATION ---
WIDTH, HEIGHT = 1080, 1920
BG_COLOR_DARK = "#121212"
BG_COLOR_LIGHT = "#F5F5F0" 
ACCENT_COLORS = ["#1DB954", "#FF4632", "#2196F3", "#FFC107", "#E91E63"]

# --- SAFE ZONE / MARGINS ---
MARGIN_X = 80
MARGIN_Y = 120
SAFE_WIDTH = WIDTH - (2 * MARGIN_X)

# --- FONT HANDLING ---
def get_font_path(bold=False):
    """Returns the best available font path on the system."""
    font_names = [
        ("Segoe UI Black.ttf", "Segoe UI Bold.ttf"),
        ("Roboto-Black.ttf", "Roboto-Bold.ttf"),
        ("HelveticaBlack.ttf", "HelveticaBold.ttf"),
        ("arialbd.ttf", "arialbd.ttf")
    ]
    for bold_name, reg_name in font_names:
        try:
            ImageFont.truetype(bold_name if bold else reg_name, 20)
            return bold_name if bold else reg_name
        except IOError:
            continue
    return "arial.ttf"

def get_font(size, bold=False):
    try:
        path = get_font_path(bold)
        return ImageFont.truetype(path, size)
    except:
        return ImageFont.load_default()

def get_scaled_font(draw, text, max_width, start_size, bold=True):
    """Iteratively scales down font until text fits width."""
    size = start_size
    font = get_font(size, bold)
    while draw.textlength(text, font) > max_width and size > 40:
        size -= 5
        font = get_font(size, bold)
    return font

# --- HELPER FUNCTIONS ---
def make_rounded(image, radius=30):
    if image is None: return None
    mask = Image.new("L", image.size, 0)
    draw = ImageDraw.Draw(mask)
    draw.rounded_rectangle((0, 0) + image.size, radius=radius, fill=255)
    output = ImageOps.fit(image, mask.size, centering=(0.5, 0.5))
    output.putalpha(mask)
    return output

def add_footer(img, theme="dark"):
    draw = ImageDraw.Draw(img)
    font_footer = get_font(30, bold=False)
    text_color = "#888888" if theme == "dark" else "#666666"
    footer_text = "Generated by TunesBack  |  github.com/mooseses/TunesBack"
    w = draw.textlength(footer_text, font_footer)
    draw.text((WIDTH//2 - w//2, HEIGHT - MARGIN_Y + 40), footer_text, font=font_footer, fill=text_color)

def create_background(theme="dark", accent_color="#1DB954"):
    bg_color = BG_COLOR_LIGHT if theme == "light" else BG_COLOR_DARK
    base = Image.new("RGBA", (WIDTH, HEIGHT), bg_color)
    
    if theme == "light":
        shape_color = (0, 0, 0, 20)
    else:
        rgb = tuple(int(accent_color.lstrip('#')[i:i+2], 16) for i in (0, 2, 4))
        shape_color = rgb + (40,) 
    
    shape_layer = Image.new("RGBA", (WIDTH, HEIGHT), (0,0,0,0))
    shape_draw = ImageDraw.Draw(shape_layer)

    for _ in range(5): 
        shape_type = random.choice(["circle", "triangle"])
        x = random.randint(-200, WIDTH)
        y = random.randint(-200, HEIGHT)
        s = random.randint(500, 1200)
        width = 20 
        
        if shape_type == "circle":
            shape_draw.ellipse((x, y, x+s, y+s), outline=shape_color, width=width)
        elif shape_type == "triangle":
            h = s * (math.sqrt(3)/2)
            p1 = (x + s/2, y)
            p2 = (x, y + h)
            p3 = (x + s, y + h)
            shape_draw.line([p1, p2, p3, p1], fill=shape_color, width=width)
    
    base = Image.alpha_composite(base, shape_layer)
    return base

# --- CARD RENDERERS ---

def draw_top_songs(items, accent_color):
    # items: list of dict {'name': str, 'sub': str, 'image': PIL.Image}
    img = create_background("dark", accent_color)
    draw = ImageDraw.Draw(img)
    
    title = "Your Top Songs"
    font_header = get_scaled_font(draw, title, SAFE_WIDTH, 130, bold=True)
    draw.text((MARGIN_X, MARGIN_Y), title, font=font_header, fill=accent_color)
    
    start_y = MARGIN_Y + 200
    row_height = 260
    
    for i, item in enumerate(items[:5]): # Limit to 5
        y = start_y + (i * row_height)
        font_rank = get_font(140, bold=True)
        draw.text((MARGIN_X, y+40), str(i+1), font=font_rank, fill="white")
        
        art_x = MARGIN_X + 140
        # Use provided image or fallback
        art = item.get('image')
        if art:
            art = art.resize((220, 220))
            art = make_rounded(art, 20)
            img.paste(art, (art_x, y), art)
        else:
            # Fallback gray box if art extraction failed
            draw.rounded_rectangle((art_x, y, art_x+220, y+220), radius=20, fill="#333")
        
        text_x = art_x + 250
        font_main = get_font(60, bold=True)
        font_sub = get_font(45, bold=False)
        
        max_text_w = (WIDTH - MARGIN_X) - text_x
        name_text = item['name']
        while draw.textlength(name_text, font=font_main) > max_text_w and len(name_text) > 0:
            name_text = name_text[:-1]
        
        draw.text((text_x, y + 40), name_text, font=font_main, fill="white")
        if 'sub' in item:
            draw.text((text_x, y + 115), item['sub'], font=font_sub, fill="#BBBBBB")
            
    add_footer(img, "dark")
    return img

def draw_top_albums(items, accent_color):
    img = create_background("dark", accent_color)
    draw = ImageDraw.Draw(img)
    
    title = "Your Top Albums"
    font_header = get_scaled_font(draw, title, SAFE_WIDTH, 130, bold=True)
    draw.text((MARGIN_X, MARGIN_Y), title, font=font_header, fill=accent_color)
    
    start_y = MARGIN_Y + 200
    gap = 15
    grid_w = SAFE_WIDTH
    w_half = (grid_w - gap) // 2
    w_third = (grid_w - (2 * gap)) // 3
    
    coords = [
        (MARGIN_X, start_y, w_half, w_half),                  
        (MARGIN_X + w_half + gap, start_y, w_half, w_half),   
        (MARGIN_X, start_y + w_half + gap, w_third, w_third), 
        (MARGIN_X + w_third + gap, start_y + w_half + gap, w_third, w_third), 
        (MARGIN_X + (w_third + gap)*2, start_y + w_half + gap, w_third, w_third) 
    ]
    
    for i, (x, y, w, h) in enumerate(coords):
        if i >= len(items) or i >= 5: break
        art = items[i].get('image')
        if art:
            art = art.resize((int(w), int(h)))
            art = make_rounded(art, radius=30)
            img.paste(art, (int(x), int(y)), art)
        else:
            draw.rounded_rectangle((x, y, x+w, y+h), radius=30, fill="#333")

    list_start_y = start_y + w_half + gap + w_third + 80
    
    for i, item in enumerate(items[:5]):
        y_pos = list_start_y + (i * 110)
        font_list_rank = get_font(60, bold=True)
        draw.text((MARGIN_X, y_pos), f"{i+1}.", font=font_list_rank, fill=accent_color)
        
        font_list_main = get_font(55, bold=True)
        draw.text((MARGIN_X + 90, y_pos), item['name'], font=font_list_main, fill="white")
        font_list_sub = get_font(40, bold=False)
        draw.text((MARGIN_X + 90, y_pos + 60), item['sub'], font=font_list_sub, fill="#888888")

    add_footer(img, "dark")
    return img

def draw_single_top_album(album_name, artist_name, minutes, image):
    img = create_background("dark", "#FF4632")
    draw = ImageDraw.Draw(img)
    
    art_w = min(800, SAFE_WIDTH)
    art_h = art_w
    spacing = 40
    
    font_title = get_font(100, bold=True)
    font_album = get_font(90, bold=True)
    font_artist = get_font(60, bold=False)
    font_stat = get_font(50, bold=False)
    
    h_title = 120
    h_album = 110
    h_artist = 80
    h_stat = 70
    
    total_h = art_h + spacing*3 + h_title + h_album + h_artist + h_stat
    available_h = HEIGHT - (2 * MARGIN_Y)
    
    if total_h > available_h:
        scale = available_h / total_h
        art_w = int(art_w * scale)
        art_h = int(art_h * scale)
        total_h = available_h 
        
    start_y = (HEIGHT - total_h) // 2
    cx = WIDTH // 2
    current_y = start_y
    
    if image:
        image = image.resize((int(art_w), int(art_h)))
        image = make_rounded(image, radius=60)
        img.paste(image, (int(cx - art_w//2), int(current_y)), image)
    else:
        draw.rounded_rectangle((cx - art_w//2, current_y, cx + art_w//2, current_y + art_h), radius=60, fill="#333")

    current_y += art_h + spacing + 40
    
    draw.text((cx, current_y), "Your Top Album", font=font_title, fill="#FF4632", anchor="mm")
    current_y += h_title + spacing
    draw.text((cx, current_y), album_name, font=font_album, fill="white", anchor="mm")
    current_y += h_album + spacing - 20
    draw.text((cx, current_y), f"by {artist_name}", font=font_artist, fill="#CCCCCC", anchor="mm")
    current_y += h_artist + spacing
    draw.text((cx, current_y), f"Listened for {minutes:,} minutes", font=font_stat, fill="white", anchor="mm")
    
    add_footer(img, "dark")
    return img

def draw_top_genres(genres):
    # genres: list of str
    img = create_background("light", "#000000")
    draw = ImageDraw.Draw(img)
    
    title = "Your Top Genres"
    font_header = get_scaled_font(draw, title, SAFE_WIDTH, 130, bold=True)
    draw.text((WIDTH//2, MARGIN_Y + 100), title, font=font_header, fill="black", anchor="mm")
    
    start_y = MARGIN_Y + 350
    for i, genre in enumerate(genres[:5]):
        font_genre = get_font(110, bold=True)
        text_w = draw.textlength(genre, font_genre)
        
        while text_w > SAFE_WIDTH and font_genre.size > 50:
            font_genre = get_font(font_genre.size - 10, bold=True)
            text_w = draw.textlength(genre, font_genre)
            
        box_h = font_genre.size + 50
        y = start_y + (i * (box_h + 40))
        cx = WIDTH // 2
        
        draw.rectangle((cx - text_w//2 - 50, y - box_h//2, cx + text_w//2 + 50, y + box_h//2), fill="black")
        draw.text((cx, y-10), genre, font=font_genre, fill="white", anchor="mm")
        
    add_footer(img, "light")
    return img

def draw_listening_age(age, subtext):
    img = create_background("light", "#FF4632")
    draw = ImageDraw.Draw(img)
    
    title = "Your Listening Age"
    font_header = get_scaled_font(draw, title, SAFE_WIDTH, 110, bold=True)
    draw.text((WIDTH//2, MARGIN_Y + 200), title, font=font_header, fill="black", anchor="mm")
    
    font_big = get_font(700, bold=True)
    draw.text((WIDTH//2, HEIGHT//2 - 50), str(age), font=font_big, fill="#FF4632", anchor="mm")
    
    font_sub = get_font(50, bold=False)
    max_width = SAFE_WIDTH 
    
    words = subtext.split()
    lines = []
    line = []
    for word in words:
        line.append(word)
        if draw.textlength(" ".join(line), font=font_sub) > max_width:
            line.pop()
            lines.append(" ".join(line))
            line = [word]
    lines.append(" ".join(line))
    
    line_y = HEIGHT//2 + 350
    for ln in lines:
        draw.text((WIDTH//2, line_y), ln, font=font_sub, fill="black", anchor="mm")
        line_y += 60
        
    add_footer(img, "light")
    return img

def draw_top_artist_spotlight(artist_name, minutes, image):
    img = create_background("dark", "#FFC107")
    draw = ImageDraw.Draw(img)
    
    cx, cy = WIDTH//2, HEIGHT//2 - 150
    max_art_size = min(700, SAFE_WIDTH)
    
    if image:
        image = image.resize((int(max_art_size), int(max_art_size)))
        mask = Image.new("L", (int(max_art_size), int(max_art_size)), 0)
        d = ImageDraw.Draw(mask)
        d.ellipse((0,0,max_art_size,max_art_size), fill=255)
        image.putalpha(mask)
        img.paste(image, (int(cx-max_art_size//2), int(cy-max_art_size//2)), image)
    else:
         draw.ellipse((cx-max_art_size//2, cy-max_art_size//2, cx+max_art_size//2, cy+max_art_size//2), fill="#333")
    
    font_title = get_font(110, bold=True)
    draw.text((cx, cy + 450), f"{artist_name} is your", font=font_title, fill="white", anchor="mm")
    draw.text((cx, cy + 570), "top artist.", font=font_title, fill="white", anchor="mm")
    
    font_sub = get_font(45, bold=False)
    msg = f"You listened for {minutes:,} minutes."
    draw.text((cx, cy + 720), msg, font=font_sub, fill="#DDDDDD", anchor="mm", align="center")
    
    add_footer(img, "dark")
    return img
